// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: network/interface/v1/interface.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkInterface_DaemonStream_FullMethodName = "/server.network.interface.v1.NetworkInterface/DaemonStream"
)

// NetworkInterfaceClient is the client API for NetworkInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkInterfaceClient interface {
	// 与 daemon 通讯的 stream 通道
	DaemonStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DaemonStreamData, DaemonStreamData], error)
}

type networkInterfaceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkInterfaceClient(cc grpc.ClientConnInterface) NetworkInterfaceClient {
	return &networkInterfaceClient{cc}
}

func (c *networkInterfaceClient) DaemonStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DaemonStreamData, DaemonStreamData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetworkInterface_ServiceDesc.Streams[0], NetworkInterface_DaemonStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DaemonStreamData, DaemonStreamData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkInterface_DaemonStreamClient = grpc.BidiStreamingClient[DaemonStreamData, DaemonStreamData]

// NetworkInterfaceServer is the server API for NetworkInterface service.
// All implementations must embed UnimplementedNetworkInterfaceServer
// for forward compatibility.
type NetworkInterfaceServer interface {
	// 与 daemon 通讯的 stream 通道
	DaemonStream(grpc.BidiStreamingServer[DaemonStreamData, DaemonStreamData]) error
	mustEmbedUnimplementedNetworkInterfaceServer()
}

// UnimplementedNetworkInterfaceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkInterfaceServer struct{}

func (UnimplementedNetworkInterfaceServer) DaemonStream(grpc.BidiStreamingServer[DaemonStreamData, DaemonStreamData]) error {
	return status.Errorf(codes.Unimplemented, "method DaemonStream not implemented")
}
func (UnimplementedNetworkInterfaceServer) mustEmbedUnimplementedNetworkInterfaceServer() {}
func (UnimplementedNetworkInterfaceServer) testEmbeddedByValue()                          {}

// UnsafeNetworkInterfaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkInterfaceServer will
// result in compilation errors.
type UnsafeNetworkInterfaceServer interface {
	mustEmbedUnimplementedNetworkInterfaceServer()
}

func RegisterNetworkInterfaceServer(s grpc.ServiceRegistrar, srv NetworkInterfaceServer) {
	// If the following call pancis, it indicates UnimplementedNetworkInterfaceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkInterface_ServiceDesc, srv)
}

func _NetworkInterface_DaemonStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NetworkInterfaceServer).DaemonStream(&grpc.GenericServerStream[DaemonStreamData, DaemonStreamData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkInterface_DaemonStreamServer = grpc.BidiStreamingServer[DaemonStreamData, DaemonStreamData]

// NetworkInterface_ServiceDesc is the grpc.ServiceDesc for NetworkInterface service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkInterface_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.network.interface.v1.NetworkInterface",
	HandlerType: (*NetworkInterfaceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DaemonStream",
			Handler:       _NetworkInterface_DaemonStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "network/interface/v1/interface.proto",
}
